name: "Create new release"
author: "action-pack"
branding:
  icon: "tag"
  color: "gray-dark"
description: "Action to create a Github release."

inputs:
  title:
    description: "The name of the release"
    default: "Name"
    required: false
  body:
    description: "The notes for the release"
    required: false
  tag:
    description: "The tagname for the release"
    required: false
  commit:
    description: "A commit hash or branch name to attach the release to"
    required: false
  token:
    description: "Repository access token"
    default: ${{ github.token }}
    required: false

runs:
  using: 'composite'
  steps:      
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_BODY: ${{ inputs.body }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_COMMIT: ${{ inputs.commit }}
