name: "Create a release"
author: "kroese"
branding:
  icon: "git-branch"
  color: "gray-dark"
description: "Publish Github releases from an action"

inputs:
  tag:
    description: "The tag of the release to publish"
    required: false
  title:
    description: "The name of the release to publish"
    required: true

runs:
  using: 'composite'
  steps:      
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_TITLE: ${{ inputs.title }}
