name: Release

on: 
  push:
    branches:
      - master
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'

jobs:
  shellcheck:
    uses: ./.github/workflows/check.yml

  release:
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Publish new version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com 
          git tag -d $(git tag | head -n 999)
          git tag -fa v4 -m "Update v4 tag"
          git push origin v4 --force
