name: Release

on: 
  push:
    branches: [ master ]
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'

jobs:
  shellcheck:
    uses: ./.github/workflows/check.yml

  integration-test:
    runs-on: ubuntu-latest
    needs: shellcheck
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Create a release
      uses: kroese/github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        title: ${{ github.sha }}

  release:
    runs-on: ubuntu-latest
    needs:
      - integration-test
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Publish new version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com       
          git tag -fa v4 -m "Update v4 tag"
          git push origin v4 --force
