name: Release

on: 
  push:
    branches:
      - master
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'

jobs:
  shellcheck:
    uses: ./.github/workflows/check.yml
    

  integration-test:
    needs: shellcheck
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Create a release
      uses: kroese/github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag: v5
        title: v5
        body: Release v5
        
  release:
    runs-on: ubuntu-latest
    needs: integration-test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Publish new version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com 
          git tag -fa v5 -m "Update v5 tag"
          git push origin v5 --force
